app = "stapply-agent"

primary_region = "iad"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [services.concurrency]
    hard_limit = 50
    soft_limit = 25
    type = "connections"

  [services.http_checks]
    interval = "10s"
    grace_period = "10s"
    method = "get"
    path = "/health"
    protocol = "http"
    restart_limit = 6
    timeout = "2s"

[checks]
  [checks.http]
    port = 8080
    type = "http"
    interval = "15s"
    timeout = "2s"
    grace_period = "10s"
    method = "get"
    path = "/health"

[processes]
  app = "uvicorn server.main:app --host 0.0.0.0 --port 8080"


